### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hugoArregui** [hugoArregui/es-querystring-parser#1]
- [x] support for [default field queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_default_field)
- [ ] support for: `title:(quick OR brown)` `title:(quick brown)`
- [ ] support for [wildcards](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_wildcards)
- [x] support for [fuzziness](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_fuzziness)
- [x] support for [proximity searches](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_proximity_searches)
- [ ] support for `age:(>=10 AND <20)` `age:(+>=10 +<20)`
- [ ] support for [boosting](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_boosting)
- [ ] support for [empty query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_empty_query)

**Comment by hugoArregui** [comment]
Moved this information to README.org in the repo
